### ISSUE TITLE
Minecraft Fabric does not start, screen stays in loading screen but without gui. (In my case grey)

### ISSUE THREAD

**Issue by TheButterbrotMan** [ejektaflex/Kambrik#10]
Kambrik-3.0.0-1.18 does not have this error, only Kambrik-3.1.0-1.18.jar

https://pastebin.com/F4RsV7FZ

**Comment by ejektaflex** [comment]
I've got to fix this - but you're right. Thank you!

**Comment by TheButterbrotMan** [comment]
Whats the ETA for the fix? Cause i want to update my modpack soon.

**Comment by ejektaflex** [comment]
Kambrik 3.0.0  and 3.1.0 do not have any feature differences as Kambrik is just a library mod, so you can continue to use the old version if you'd like.

However, I've uploaded a new version of Bountiful that works with Kambrik 3.1.0, and it will be available once they are done reviewing it. Thanks!
