### ISSUE TITLE
Calling LoggerContext#reconfigure breaks other mods

### ISSUE THREAD

**Issue by DJtheRedstoner** [ejektaflex/Kambrik#17]
https://github.com/ejektaflex/Kambrik/blob/2dbb5d920ca4c8ca771ee14916f5583c599b41a1/src/main/java/io/ejekta/kambrik/internal/KambrikPrelaunch.kt#L42

This causes all logger configurations to be reloaded, meaning any in-memory changes made by other mods will be lost. This call is not needed, it can be removed without any replacement.

**Comment by ejektaflex** [comment]
Thanks - I've got that sorted for the new release.
