### ISSUE TITLE
I got an issue when using it.

### ISSUE THREAD

**Issue by SirPytan** [ejektaflex/Kambrik#6]
Here the Log file, I will also add a screenshot: https://paste.ee/p/1nJFK

![image](https://user-images.githubusercontent.com/38554289/134257657-8f20b124-fc9f-4b3e-8213-a9ba14b2e9dd.png)

**Comment by SirPytan** [comment]
Ok, thanks, did you transfer it to their Github?

**Comment by ejektaflex** [comment]
I did not - but I saw that you did - thank you for doing so!
